server:
  port: 8081
spring:
  datasource:
   # url: jdbc:mysql://tramway.proxy.rlwy.net:49913/railway?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/matching_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    #password: mZQqnNdUhqQiefyVVYKVTdgOkovGHlpu
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: exchange-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.ExchangeService.ExchangeService.events.EventEnvelope

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

finnhub:
  api:
    key: d36mrn9r01qtvbtic7tgd36mrn9r01qtvbtic7u0

logging:
  level:
    org.apache.kafka: warn
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: warn
    org.apache.kafka.clients.consumer.internals.ConsumerUtils: warn
    org.apache.kafka.clients.Metadata: warn

stocks:
  symbols: AAPL,GOOG,TSLA,MSFT,AMZN






